CREATE TABLE withdrawal_notice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   notice_date date,
   withdrawal_amount DOUBLE PRECISION NOT NULL,
   product_id BIGINT,
   CONSTRAINT pk_withdrawalnotice PRIMARY KEY (id)
);

ALTER TABLE withdrawal_notice ADD CONSTRAINT FK_WITHDRAWALNOTICE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);